### PR TITLE
Catch SystemCallError, in case command doesn't exist

### LINKED ISSUE #264: Show error message for `createdb` failure
I'm using [Postgres.app](http://postgresapp.com/) on OS X, and I just ran into a problem running `lotus db create`

```
 ~> lotus db create
/Users/sean/.gem/ruby/2.1.6/gems/lotus-model-0.5.0/lib/lotus/model/migrator/postgres_adapter.rb:29:in ``': No such file or directory - createdb (Errno::ENOENT)
	from /Users/sean/.gem/ruby/2.1.6/gems/lotus-model-0.5.0/lib/lotus/model/migrator/postgres_adapter.rb:29:in `create'
	from /Users/sean/.gem/ruby/2.1.6/gems/lotus-model-0.5.0/lib/lotus/model/migrator.rb:84:in `create'
	from /Users/sean/.gem/ruby/2.1.6/gems/lotusrb-0.5.0/lib/lotus/commands/db/create.rb:9:in `start'
	from /Users/sean/.gem/ruby/2.1.6/gems/lotusrb-0.5.0/lib/lotus/commands/db.rb:31:in `create'
	from /Users/sean/.gem/ruby/2.1.6/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/sean/.gem/ruby/2.1.6/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/sean/.gem/ruby/2.1.6/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/sean/.gem/ruby/2.1.6/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/sean/.gem/ruby/2.1.6/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
```

The problem was that running the `createdb ...` on my computer didn't succeed. I needed to follow [these directions](http://postgresapp.com/documentation/cli-tools.html) (i.e. add `createdb` to my PATH) in order to make it work.

Related: #200, #262

I solved it by looking at `postgres_adapter.rb`, but should we see if `createdb` fails, and show an error saying 'running `createdb` failed` instead of the above?

### PR DESCRIPTION
**Pull request by cllns**
Closes #264.

I don't really like that we basically just change the `SystemCallError` into a `MigrationError`, without rescuing it, but that seems like another PR :)

### CODE REVIEW

File: test/integration/migration/postgres_test.rb [hunk 1]
```diff
@@ -71,6 +71,23 @@
...
+      describe "when a command isn't available" do
+        before do
+          # We accomplish having a command not be available by setting PATH
+          # to an empty string, which means *no commands* are available.
+          @original_path = ENV['PATH']
+          ENV['PATH'] = ''
+        end
+
+        it "raises MigrationError on create" do
+          -> { Lotus::Model::Migrator.create }.must_raise Lotus::Model::MigrationError
```
Comment (joneslee85) [inline test/integration/migration/postgres_test.rb]: can we asset the exception message too?
