### PR TITLE
[WIP] Add block conditions to where on memory adapter

### LINKED ISSUE #165: Trouble using expressions in `where`
I have the following in my repository based on #46 
```ruby
class OrderRepository
  def since(date)
    query do
      where{ created_at > date }
    end
  end
end
```
But I'm receive the following error:

```bash
     Failure/Error: recent_orders = OrderRepository.since(yesterday)                                                                                                                                       │
     ArgumentError:                                                                                                                                                                                        │
       wrong number of arguments (0 for 1)                                                                                                                                                                 │
     # ./repositories/order_repository.rb:15:in `block in since'                                                                                                                                           │
     # ./repositories/order_repository.rb:14:in `since'                                                                                                                                                    │
     # ./spec/repositories/order_repository_spec.rb:23:in `block (3 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by guilhermeFranco**
**[WIP]** Closes #165 

Hey guys, this is my **initial** :yum: implementation of the block conditions in our memory adapter. I decided to open this early PR to get some thoughts from you about my design decisions. 

The next steps for this feature would be to extract some private methods from `#where`, since it's getting longer than it should be (and it really bothers me to use `elsif` :hamster:). Finally, change both #or and #exclude in order to allow block conditions as well. But before all that, I want to know if my `OpenStruct` approach is good enough for me to continue with this design. 

I decided to use it since the other alternative I came up with was to deserialize the entities and perform the `find_all` search (since the block uses methods and not hash keys), and I really think that this is not a good approach. 

If you guys have a better idea please let me know, and I will continue with the refactors and remaining changes in `#or` and `#exclude`.

Thanks !

### CODE REVIEW

**Comment by guilhermeFranco** [comment]
@joneslee85 @jodosha Looks good so far ? May I proceed with this approach ? :hamburger:

**Comment by joneslee85** [comment]
This is an interesting feature. I have no time today to look into it yet, but worth to catch up with you on this tomorrow.

**Comment by jodosha** [comment]
@guilhermeFranco The trick looks good and very clever :+1: 

There is one behavior to make consistent between memory and SQL adapter. When you use an unknown column, it raises **a cryptic error**:

```ruby
        it 'accepts a block as condition' do
          query  = Proc.new {
            where{ a > 31 } # WRONG NAME a INSTEAD OF age
          }

          result = @adapter.query(collection, &query).all
          result.must_equal [@user1]
        end

```

Produces:

```
  1) Error:
Lotus::Model::Adapters::MemoryAdapter::#query::where::with a filled collection#test_0008_accepts a block as condition:
NoMethodError: undefined method `>' for nil:NilClass
    /Users/luca/Code/lotus/model/test/model/adapters/memory_adapter_test.rb:363:in `block (7 levels) in <top (required)>'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/memory/query.rb:131:in `instance_eval'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/memory/query.rb:131:in `block (2 levels) in where'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/memory/query.rb:131:in `each'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/memory/query.rb:131:in `find_all'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/memory/query.rb:131:in `block in where'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/memory/query.rb:538:in `instance_exec'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/memory/query.rb:538:in `block in run'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/memory/query.rb:534:in `each'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/memory/query.rb:534:in `run'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/memory/query.rb:71:in `all'
    /Users/luca/Code/lotus/model/test/model/adapters/memory_adapter_test.rb:366:in `block (5 levels) in <top (required)>'
```

If we do the same thing for SQL adapter, it raises a totally different error.

```
  2) Error:
Lotus::Model::Adapters::SqlAdapter::#query::where::with a filled collection#test_0004_can use lambda to describe where conditions:
Sequel::DatabaseError: SQLite3::SQLException: no such column: a
    /Users/luca/.gem/ruby/2.2.2/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `initialize'
    /Users/luca/.gem/ruby/2.2.2/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `new'
    /Users/luca/.gem/ruby/2.2.2/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `prepare'
    /Users/luca/.gem/ruby/2.2.2/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:266:in `query'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/adapters/sqlite.rb:185:in `block (2 levels) in _execute'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/database/logging.rb:33:in `log_yield'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/adapters/sqlite.rb:185:in `block in _execute'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/connection_pool/threaded.rb:98:in `hold'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/database/connecting.rb:250:in `synchronize'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/adapters/sqlite.rb:178:in `_execute'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/adapters/sqlite.rb:128:in `execute'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/dataset/actions.rb:911:in `execute'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/adapters/sqlite.rb:362:in `fetch_rows'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/dataset/actions.rb:139:in `each'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/dataset/actions.rb:390:in `map'
    /Users/luca/.gem/ruby/2.2.2/gems/sequel-4.21.0/lib/sequel/dataset/actions.rb:390:in `map'
    /Users/luca/Code/lotus/model/lib/lotus/model/mapping/collection.rb:354:in `deserialize'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/sql/collection.rb:198:in `to_a'
    /Users/luca/.gem/ruby/2.2.2/bundler/gems/utils-6dbb81dd7b74/lib/lotus/utils/kernel.rb:82:in `Array'
    /Users/luca/.gem/ruby/2.2.2/bundler/gems/utils-6dbb81dd7b74/lib/lotus/utils/kernel.rb:82:in `Array'
    /Users/luca/Code/lotus/model/lib/lotus/model/adapters/sql/query.rb:75:in `all'
    /Users/luca/Code/lotus/model/test/model/adapters/sql_adapter_test.rb:331:in `block (5 levels) in <top (required)>'
```

We should introduce a new error type: `Lotus::Model::UnknownAttributeError` or `Lotus::Model::InvalidQueryError` and make sure that both the adapters will raise the same error with a descriptive message.

/cc @joneslee85 Thoughts about the exception name?

**Comment by joneslee85** [comment]
InvalidQueryError has my vote.

**Comment by guilhermeFranco** [comment]
@jodosha I agree with @joneslee85. I will add `Lotus::Model::InvalidQueryError` and change SQL adapter to use it too. :+1:

**Comment by guilhermeFranco** [comment]
@joneslee85 @jodosha Hey guys, just realized some things about the error raising thing while working on the code and want some thoughts before I proceed: 

1. With the SQL adapter, it's all about getting the exception message that comes from Sequel and re-raise it as Lotus::Model::InvalidQueryError. So, it's all good. But when we move to the memory adapter, there's no way to describe accurately what the query error was (since it is just a block being executed, and the error we'll get will likely be a `NoMethodError` as @jodosha pointed out). So, what you guys think would be a nice default error message for this case ? Or should we just leave without a message in this case ?

2. I put the error handling of SQL adapter on `Lotus::Model::Adapters::Sql::Collection#to_a` since it's the exact place where records are fetched from the database, so it's looking like this now: (Should I change it to be somewhere else ?)

```ruby
def to_a            
  @mapped_collection.deserialize(self)
rescue Sequel::DatabaseError => e
  raise Lotus::Model::InvalidQueryError.new(e.message)
end
```

3. There will be a know limitation for the block conditions on the memory adapter, and it's Ruby's fault :cry: If we call `==` on an nonexistent method / attribute of a `OpenStruct`, we get `false` as a result, instead of a `NoMethodError`. In this case, if we perform the following query:

```ruby
query  = Proc.new {
  where { a == 31 } # WRONG NAME a INSTEAD OF age
}

result = @adapter.query(collection, &query).all
# => []
```

We will get an empty array instead of `Lotus::Model::InvalidQueryError`. Do you guys think this is an issue ? I really don't think there is a better way to treat this edge case.

Thank you guys for your patience ! I'm working hard to make this thing done the right way.

**Comment by guilhermeFranco** [comment]
@jodosha @joneslee85 Hey guys ! Sorry about the delay !

I've added more commits to this feature and it is now complete. Please let me know your thoughts and, if it's all good, I'll add the API docs for the methods.

File: lib/lotus/model/adapters/memory/query.rb [hunk 1]
```diff
@@ -94,22 +95,41 @@ def all
...
+          #
+          #   query.where(language: 'ruby')
+          #        .where { framework == 'lotus' }
+          def where(condition = nil, &blk)
+            if blk
+              _push_evaluated_block_condition(:where, blk)
+            elsif condition
+              _push_to_expanded_condition(:where, condition) do |column, value|
+                Proc.new {
+                  find_all{ |r|
```
Comment (joneslee85) [inline lib/lotus/model/adapters/memory/query.rb]: nitpick, add a space before `{`

File: lib/lotus/model.rb [hunk 2]
```diff
@@ -27,6 +27,16 @@ class NonPersistedEntityError < ::StandardError
     class InvalidMappingError < ::StandardError
     end
 
+    # Error for invalid query
+    # It's raised when a query is malformed
+    #
+    # @since 0.3.1
```
Comment (joneslee85) [inline lib/lotus/model.rb]: it is unlikely to be in 0.3.1, please change it to x.x.x

File: lib/lotus/model/adapters/memory/query.rb [hunk 3]
```diff
@@ -94,22 +95,41 @@ def all
...
+                    case value
+                    when Array,Set,Range
+                      value.include?(r.fetch(column, nil))
```
Comment (joneslee85) [inline lib/lotus/model/adapters/memory/query.rb]: you can extract `r.fetch(column, nil)` to a variable since it's repeated twice

File: test/model/adapters/memory_adapter_test.rb [hunk 4]
```diff
@@ -357,6 +357,43 @@ class TestDeviceRepository
           result = @adapter.query(collection, &query).all
           result.must_equal [@user2, @user3]
         end
+
+        it 'accepts a block as condition' do
+          query  = Proc.new {
+            where{ age > 31 }
```
Comment (joneslee85) [inline test/model/adapters/memory_adapter_test.rb]: nitpick, add space before `{`

File: lib/lotus/model/adapters/memory/query.rb [hunk 5]
```diff
@@ -141,9 +161,15 @@ def where(condition)
...
           #   query.where(country: 'italy').or(year: 1900..1982)
-          def or(condition=nil, &blk)
-            column, value = _expand_condition(condition)
-            conditions.push([:or, Proc.new{ find_all{|r| r.fetch(column) == value} }])
+          def or(condition = nil, &blk)
+            if blk
+              _push_evaluated_block_condition(:or, blk)
+            elsif condition
+              _push_to_expanded_condition(:or, condition) do |column, value|
+                Proc.new { find_all{ |r| r.fetch(column) == value} }
```
Comment (joneslee85) [inline lib/lotus/model/adapters/memory/query.rb]: nitpick, add space after `find_all`

File: lib/lotus/model/adapters/memory/query.rb [hunk 6]
```diff
@@ -175,9 +201,15 @@ def or(condition=nil, &blk)
           #
           #   query.exclude(language: 'java')
           #        .exclude(company: 'enterprise')
```
Comment (joneslee85) [inline lib/lotus/model/adapters/memory/query.rb]: please add doc

File: lib/lotus/model/adapters/memory/query.rb [hunk 7]
```diff
@@ -141,9 +161,15 @@ def where(condition)
           # @example Range
           #
           #   query.where(country: 'italy').or(year: 1900..1982)
```
Comment (joneslee85) [inline lib/lotus/model/adapters/memory/query.rb]: please add doc

File: lib/lotus/model.rb [hunk 8]
```diff
@@ -27,6 +27,16 @@ class NonPersistedEntityError < ::StandardError
...
+    class InvalidQueryError < ::StandardError
+      def initialize(message = nil)
```
Comment (joneslee85) [inline lib/lotus/model.rb]: it seems to me there is no case where message is nil, should we remove the default message?

File: test/model/adapters/memory_adapter_test.rb [hunk 9]
```diff
@@ -357,6 +357,43 @@ class TestDeviceRepository
...
+          result = @adapter.query(collection, &query).all
+          result.must_equal [@user1]
+        end
+
+        it "raises InvalidQueryError when columns are invalid in expression" do
+          query  = Proc.new {
+            where { a > 32 }
+          }
+
+          -> {
```
Comment (joneslee85) [inline test/model/adapters/memory_adapter_test.rb]: please also add test to check the exception message

File: test/model/adapters/memory_adapter_test.rb [hunk 10]
```diff
@@ -414,6 +451,43 @@ class TestDeviceRepository
           result = @adapter.query(collection, &query).all
           result.must_equal [@user3]
         end
+
+        it 'accepts a block as condition' do
+          query  = Proc.new {
+            exclude{ age > 31 }
```
Comment (joneslee85) [inline test/model/adapters/memory_adapter_test.rb]: nitpick, add space before `{`

File: test/model/adapters/memory_adapter_test.rb [hunk 11]
```diff
@@ -414,6 +451,43 @@ class TestDeviceRepository
...
+          result = @adapter.query(collection, &query).all
+          result.must_equal [@user2, @user3]
+        end
+
+        it "raises InvalidQueryError when columns are invalid in expression" do
+          query  = Proc.new {
+            exclude { a > 32 }
+          }
+
+          -> {
```
Comment (joneslee85) [inline test/model/adapters/memory_adapter_test.rb]: please also add test to check the exception message

File: test/model/adapters/memory_adapter_test.rb [hunk 12]
```diff
@@ -456,6 +531,43 @@ class TestDeviceRepository
...
+          result = @adapter.query(collection, &query).all
+          result.must_equal [@user2, @user1]
+        end
+
+        it "raises InvalidQueryError when columns are invalid in expression" do
+          query  = Proc.new {
+            where(name: "MG").or { a > 31 }
+          }
+
+          -> {
```
Comment (joneslee85) [inline test/model/adapters/memory_adapter_test.rb]: please also add test to check the exception message

File: test/model/adapters/sql_adapter_test.rb [hunk 13]
```diff
@@ -332,6 +332,15 @@ class TestDeviceRepository
           result.must_equal [@user1]
         end
 
+        it 'raises InvalidQueryError if you use wrong column names' do
+          -> {
```
Comment (joneslee85) [inline test/model/adapters/sql_adapter_test.rb]: please also add test to check the exception message

File: test/model/adapters/sql_adapter_test.rb [hunk 14]
```diff
@@ -398,6 +407,14 @@ class TestDeviceRepository
           result.must_equal [@user3]
         end
 
+        it 'raises InvalidQueryError if you use wrong column names' do
+          -> {
```
Comment (joneslee85) [inline test/model/adapters/sql_adapter_test.rb]: please also add test to check the exception message

File: test/model/adapters/sql_adapter_test.rb [hunk 15]
```diff
@@ -468,6 +485,19 @@ class TestDeviceRepository
             @adapter.query(collection, &query).all
           }.must_raise(ArgumentError)
         end
+
+        it 'raises InvalidQueryError if you use wrong column names' do
+          -> {
```
Comment (joneslee85) [inline test/model/adapters/sql_adapter_test.rb]: please also add test to check the exception message

File: lib/lotus/model.rb (hunk 8 above)
Comment (guilhermeFranco) [inline lib/lotus/model.rb]: Actually, there is :cry: When thrown from the memory adapter, the message would be cryptic, as @jodosha pointed out. In this case, I thought the default message would be better than `InvalidQueryError: undefined method `>' for nil:NilClass`

**Comment by joneslee85** [comment]
> With the SQL adapter, it's all about getting the exception message that comes from Sequel and re-raise it as Lotus::Model::InvalidQueryError. So, it's all good. But when we move to the memory adapter, there's no way to describe accurately what the query error was (since it is just a block being executed, and the error we'll get will likely be a NoMethodError as @jodosha pointed out). So, what you guys think would be a nice default error message for this case ? Or should we just leave without a message in this case ?

It's worth to raise exceptions instead of leaving it without any messages. How many exceptions that MemAdapter could yield? We can try to _Gotta catch 'em all(tm)_

**Comment by guilhermeFranco** [comment]
@joneslee85 LOL ! MemAdapter may yield some `NoMethodError` exceptions when we try to perform a query with a block containing wrong attribute names. That's why I've re-raised them as `Lotus::Model::InvalidQueryError` on `#_push_evaluated_block_condition`. 

I'm actually wondering what the message should be. When we re-raise a SQLAdapter exception, it will have a nice descriptive message, since it's a `Sequel` error. But for MemAdapter, raising a `Lotus::Model::InvalidQueryError` with a message being something like `undefined method....for NilClass` seems a bit unclear to me. That's why I've decided to add a default message for this exception.

**Comment by joneslee85** [comment]
@guilhermeFranco what about raising message that `Attribute abc is undefined. Please check your query.` instead?

**Comment by guilhermeFranco** [comment]
@joneslee85 It would be a lot better indeed. The problem is figuring out what attribute is wrong, since it's a block execution with a cryptic `NoMethodError` error message :disappointed: Do you have any thoughts about this ?

**Comment by joneslee85** [comment]
@guilhermeFranco nope, :(

**Comment by guilhermeFranco** [comment]
@joneslee85 @jodosha So, if we are not able to determine exactly which attribute is wrong, what would be a nice default message for the user ? That's my main doubt :(

**Comment by joneslee85** [comment]
@guilhermeFranco I think for now we can leave it as is, a vague message like 'Invalid query' and put a TODO note to revisit this in the future

**Comment by guilhermeFranco** [comment]
@joneslee85 Sounds good to me. Will do it asap ! Thank you for your support !

**Comment by guilhermeFranco** [comment]
@joneslee85 I've made the suggested changes, and now I think we're good to go. Can you please take a look to see if I'm missing something ? Thank you for your time and patience !

**Comment by joneslee85** [comment]
@guilhermeFranco :+1: to me, waiting for one last round review from @jodosha @AlfonsoUceda and whom who are interested in this

**Comment by jodosha** [comment]
@guilhermeFranco Thank you, it looks good now. Just merged it! :+1:

/cc @joneslee85

**Comment by cgarvis** [comment]
Thanks @guilhermeFranco!

**Comment by guilhermeFranco** [comment]
@jodosha @cgarvis You're welcome guys ! Glad to help :)

File: lib/lotus/model/adapters/memory/query.rb [hunk 16]
```diff
@@ -94,22 +95,41 @@ def all
...
+          def where(condition = nil, &blk)
+            if blk
+              _push_evaluated_block_condition(:where, blk, :find_all)
+            elsif condition
+              _push_to_expanded_condition(:where, condition) do |column, value|
+                Proc.new {
+                  find_all { |r|
+                    case value
+                    when Array,Set,Range
+                      value.include?(r.fetch(column, nil))
```
Comment (brokenladder) [inline lib/lotus/model/adapters/memory/query.rb]: Replace Conditional With Polymorphism

Comment (guilhermeFranco) [inline lib/lotus/model/adapters/memory/query.rb]: @brokenladder Feel free to submit a PR :+1:
