### PR TITLE
Fix for Dirty tracking inplace modifications

### LINKED ISSUE #186: Dirty tracking should compare entire object attribute hash
Here's what happens when you bypass lotus attr writers when mutating an enitity:

``` ruby
require 'lotus-model'

class Post
  include Lotus::Entity
  include Lotus::Entity::DirtyTracking
  attributes :title, :tags
end

post = Post.new title: 'foo', tags: %w(red green)

puts post.changed? # false

post.tags << 'blue'
puts post.tags.inspect # ["red", "green", "blue"]

puts post.changed? # false
puts post.changed_attributes.inspect # {}
```

The only way to make it reliable is to compare entire attribute hash, it'll be slower but at least stable.

### PR DESCRIPTION
**Pull request by dsnipe**
It also fixes some wrong tests – `#changed_attributes` should show changed attributes with previous values.

Closes #186

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
@dsnipe there is a problem with changed attributes:
```ruby
require 'lotus-model'

class Post
  include Lotus::Entity
  include Lotus::Entity::DirtyTracking
  attributes :title, :tags
end

post = Post.new title: 'foo', tags: %w(red green)

puts post.changed? # false

post.tags << 'blue'
puts post.tags.inspect
post.changed_attributes.inspect # => {:tags=>["red", "green"]}
post.title = "new title"
post.changed_attributes.inspect # => {:title=>"foo"}
```

do you see changed_attributes only save the last changed attribute?

**Comment by dsnipe** [comment]
hmm... I'll check this today
thanks @AlfonsoUceda

**Comment by dsnipe** [comment]
@AlfonsoUceda you may continue reviewing :)

File: lib/lotus/entity/dirty_tracking.rb [hunk 1]
```diff
@@ -2,11 +2,11 @@ module Lotus
   module Entity
     # Dirty tracking for entities
     #
-    # @since 0.3.1
+    # @since x.x.x
```
Comment (AlfonsoUceda) [inline lib/lotus/entity/dirty_tracking.rb]: I'll keep 0.3.1 version because the public API didn't change

File: lib/lotus/entity/dirty_tracking.rb [hunk 2]
```diff
@@ -2,11 +2,11 @@ module Lotus
...
     module DirtyTracking
-      # Override setters for attributes to support dirty tracking
+      # Support dirty tracking
       #
-      # @since 0.3.1
+      # @since x.x.x
```
Comment (AlfonsoUceda) [inline lib/lotus/entity/dirty_tracking.rb]: I'll keep 0.3.1 version because the public API didn't change

File: lib/lotus/entity/dirty_tracking.rb [hunk 3]
```diff
@@ -25,46 +25,19 @@ module DirtyTracking
...
-        end
-      end
+      attr_reader :init_state
 
       # Override initialize process.
       #
       # @param attributes [Hash] a set of attribute names and values
       #
-      # @since 0.3.1
+      # @since x.x.x
```
Comment (AlfonsoUceda) [inline lib/lotus/entity/dirty_tracking.rb]: I'll keep 0.3.1 version because the public API didn't change

File: lib/lotus/entity/dirty_tracking.rb [hunk 4]
```diff
@@ -73,12 +46,12 @@ def initialize(attributes = {})
       #
       # @return [::Hash] the changed attributes
       #
-      # @since 0.3.1
+      # @since x.x.x
```
Comment (AlfonsoUceda) [inline lib/lotus/entity/dirty_tracking.rb]: I'll keep 0.3.1 version because the public API didn't change

File: lib/lotus/entity/dirty_tracking.rb [hunk 5]
```diff
@@ -91,35 +64,34 @@ def initialize(attributes = {})
...
+        diff = @init_state.to_a - _current_state.to_a
+        Hash[diff]
       end
 
       # Checks if the attributes were changed
       #
       # @return [TrueClass, FalseClass] the result of the check
       #
-      # @since 0.3.1
+      # @since x.x.x
```
Comment (AlfonsoUceda) [inline lib/lotus/entity/dirty_tracking.rb]: I'll keep 0.3.1 version because the public API didn't change

**Comment by AlfonsoUceda** [comment]
I'll change the position of https://github.com/dsnipe/model/blob/refactoring-dirty-tracking/lib/lotus/entity/dirty_tracking.rb#L7-L27 to https://github.com/dsnipe/model/blob/refactoring-dirty-tracking/lib/lotus/entity/dirty_tracking.rb#L3

File: lib/lotus/entity/dirty_tracking.rb [hunk 6]
```diff
@@ -25,46 +25,19 @@ module DirtyTracking
...
 
-          class_eval %{
-            def #{ attr }=(value)
-              _attribute_changed(:#{ attr }, @#{ attr }, value)
-              @#{ attr } = value
-            end
-          }
-        end
-      end
+      attr_reader :init_state
```
Comment (AlfonsoUceda) [inline lib/lotus/entity/dirty_tracking.rb]: comment this attr_reader

Comment (dsnipe) [inline lib/lotus/entity/dirty_tracking.rb]: That how I'm protect initial state (@init_state) of entity from outside modifications. But now I thinking that it can conflict with users methods and better hide it state somehow. 
Or we can put it in public API to show init state (then better to rename it to @init_attributes). 
Also it's possible to implement #revert! that can restore entity to initial state in separate PR (not sure it should be).
What do you think?

Comment (AlfonsoUceda) [inline lib/lotus/entity/dirty_tracking.rb]: IMO I think you don't protect, an example:
```ruby
post.init_state # => {:id=>nil, :title=>"foo", :tags=>["red", "green"]} 
post.init_state = 123123 #=> NoMethodError: undefined method `init_state=' for #<Post:0x007fefb3a456f0>
post.instance_variable_get(:@init_state) # => {:id=>nil, :title=>"foo", :tags=>["red", "green"]}
post.instance_variable_set(:@init_state, 'fwefwefw')
post.init_state # => "fwefwefw"
```
maybe I'm losing something

Comment (dsnipe) [inline lib/lotus/entity/dirty_tracking.rb]: You're right. But instance variable always public, so it's possible to protect only getters/setters methods.
Maybe you have any suggestions how to store the initial state in immutable way?

**Comment by jodosha** [comment]
@dsnipe I think this is getting convoluted. The introduction of another ivar to track the state is a smell.
I'd follow @solnic suggestion reported in #186 

> The only way to make it reliable is to compare entire attribute hash, it'll be slower but at least stable.

To clarify, he's referring to `Object#hash` comparison.

**Comment by solnic** [comment]
The only way to make this stable is to compare original "raw state" with the current one. "raw state" means attributes that are going to be persisted. Since entities are decoupled from repositories you're going to have hard time making robust dirty tracking. IMO a repository should be responsible for telling if an object is dirty or not.

**Comment by dsnipe** [comment]
@jodosha I understand what you mean. It's smells for me too. I was looking for a "easy way", but as noted @solnic, it's more complicated than it seems at first glance. 
I'll make research on this when will have some time (after my wedding on this Saturday, I hope at least I'll have it :)

**Comment by jodosha** [comment]
@dsnipe OMG Best wishes!! :wedding: :ring: Don't care about this, I'll figure out. Enjoy your honeymoon :honey_pot:  :full_moon:

**Comment by dsnipe** [comment]
@jodosha thank you! :sunny: 
Working on this project is a pleasure for me, so It'll no problem to take some time. My future wife understands that marries on developer :)
Anyway it'll be great if you can put somewhere your strategic vision about Models (for developing process). Than it'll be easy to understand what functionality important and should be in core, and what is not so and might be as plugin and so on. 
I want to be more involved in that project and that kind of understanding important for me, so I'll be very appreciated if you can find time and share your thoughts.

**Comment by joneslee85** [comment]
@dsnipe Congrats

**Comment by jodosha** [comment]
@dsnipe I merged this thank you. Make it work is more important of the internal design. I've did some refactoring here https://github.com/lotus/model/commit/a230aeaae3a1098136f3d0087074105505a3696f
